site_name: STFC Azimuth Science Platform
repo_url: https://github.com/stfc/cloud-azimuth-user-docs
copyright: |
  Copyright &copy; 2025 Science and Technology Facilities Council</br>
  Licensed under the Apache License, Version 2.0.
edit_uri: ''
nav:
  - 'Introduction': 'index.md'
  - 'Platforms':
    - 'Kubernetes':
      - 'Overview': 'platforms/kubernetes.md'
      - 'Kubernetes Applications': 
        - 'ArgoCD': 'platforms/kubernetes-applications/argocd.md'
        - 'BinderHub': 'platforms/kubernetes-applications/binderhub.md'
        - 'DaskHub': 'platforms/kubernetes-applications/daskhub.md'
        - 'HuggingFace LLM': 'platforms/kubernetes-applications/huggingface-llm.md'
        - 'JupyterHub': 'platforms/kubernetes-applications/jupyterhub.md'
        - 'KubeFlow': 'platforms/kubernetes-applications/kubeflow.md'
      - 'Kubernetes Cluster Addons':
        - 'Kubernetes Dashboard': 'platforms/kubernetes-cluster-addons/kubernetes_dashboard.md'
        - 'Monitoring': 'platforms/kubernetes-cluster-addons/monitoring.md'
    # - 'Linux Workstation': 'platforms/linux-workstation.md'
    # - 'Jupyter Notebook': 'platforms/jupyter-notebook.md'
    # - 'Slurm': 'platforms/slurm.md'
  - 'Identity Provider': 'identity_provider/identity_provider.md'
  - 'Quotas': 'quotas/quotas.md'
  - 'Advanced':
    - 'Machines': 'advanced/machines.md'
    - 'Volumes': 'advanced/volumes.md'
  - 'Known Issues': 'known_issues/known_issues.md'

theme:
  features:
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/images/Cloud-Logo-Square.png
  favicon: assets/images/UKRI_STFC_Square_RGB.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
      accent: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/overrides/.icons
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - sane_lists
  - footnotes

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - search
